### ISSUE TITLE
install with pip 8.0.2 fails on OS X 10.11.3

### ISSUE THREAD

**Issue by notnami** [spacy-io/spaCy#250] opened 2016-02-06 18:32 UTC
Hi,

I posted about this problem in another issue, but that issue was closed, and I didn't want it to get lost there.

I am trying to install spacy 0.100.3 on a venv with pip 8.0.2 (OS X 10.11.3), and get an installation error:

    fatal error: 'endian.h' file not found

Numpy is installed. I have spent a while rm-ing and reinstalling the virtual environments, trying various combinations of venv and virtualenv and even conda (which doesn't seem to have the latest version of spacy), but nothing has helped. I tried another OS X machine and ran into the same problem there. Any ideas?

**Comment by notnami** [comment] 2016-02-06 18:47
Well, this is strange. When I forced pip to install 0.100.2, everything installed correctly. So something doesn't work only with the latest version?

**Comment by honnibal** [comment] 2016-02-06 18:53
Damn, I think I messed up this release. There's a cross-platform build issue we hit in 0.100.1, that we fixed in 0.100.2. But I think I reintroduced the bug. Thanks for the report, will fix.

0.100.3 actually has some important stuff --- massive load time improvement, and multi-threading. It's only versioned weirdly because we're gearing up for a 1.0 release :). So, I'll get this fixed and push out a 0.100.4.

**Comment by notnami** [comment] 2016-02-06 18:56
Yeah, I was actually excited for multi-threading (I've had to write all sorts of hacky ways to get past that before) and reduced load times. So I hope this new release fixes this strange install bug. Thanks for the quick response!

**Comment by honnibal** [comment] 2016-02-06 19:02
You can probably build from source in the meantime.

The issue is that we copy in some numpy headers, and we didn't realise these have a platform-specific option. So, we accidentally made the distribution platform specific. We built the distribution on our server, which is why it failed on OSX.

**Comment by honnibal** [comment] 2016-02-07 01:02
Try now

**Comment by derickl** [comment] 2016-02-07 09:54
Something else broke.

` spacy/tagger.cpp:251:10: fatal error: 'cblas.h' file not found
    #include "cblas.h"
             ^
    1 error generated.
    error: command 'gcc' failed with exit status 1`

**Comment by honnibal** [comment] 2016-02-07 12:53
Dammit. Too hasty.

Should work now, uploaded 0.100.5

**Comment by derickl** [comment] 2016-02-07 15:45
FIXED!
Thank you for the quick turnaround @honnibal

**Comment by honnibal** [comment] 2016-02-07 16:28
No worries, thanks for reporting!

**Closed by honnibal** 2016-02-07 16:28 UTC
