### ISSUE TITLE
How can I use simpler Google Universal POS Tag set 

### ISSUE THREAD

**Issue by yiwenliu** [spacy-io/spaCy#399] opened 2016-05-30 07:03 UTC
Hi,

On the DOCS page on spacy.io, I saw that "Spacy also map the tags to the simpler Google Universal POS Tag set", then I opened the tagger.pyx on github and just want to figure out whether to move the first line after "# TODO: Move this to tag map", or the whole four lines after it?

Thank you so much.

**Comment by honnibal** [comment] 2016-08-23 17:04
Hi,

Sorry I'm only getting to this now. I'm not sure I understand the question.

You can access the fine-grained tag at `token.tag_` in the Python API, and access the coarse-grained tag at `token.pos_`. Do you need to change the POS mapping?

I'll close this because the issue is old, but please do reply if it's not clear. Thanks.

**Closed by honnibal** 2016-08-23 17:04 UTC
