### ISSUE TITLE
AssertionError on multiple dots

### ISSUE THREAD

**Issue by acohan** [spacy-io/spaCy#419] opened 2016-06-09 19:20 UTC
When there are more than 5 consecutive dots in a string, Spacy throws AssertionError. 5 or less dots are ok.

```
from spacy.en import English
nlp = English()
nlp(u'some.....dots')
out: some.....dots
nlp(u'some......dots')

  File "python2.7/site-packages/spacy/language.py", line 225, in __call__
    tokens = self.tokenizer(text)
  File "spacy/tokenizer.pyx", line 132, in spacy.tokenizer.Tokenizer.__call__ (spacy/tokenizer.cpp:4835)
  File "spacy/tokenizer.pyx", line 159, in spacy.tokenizer.Tokenizer._tokenize (spacy/tokenizer.cpp:5409)
  File "spacy/tokenizer.pyx", line 231, in spacy.tokenizer.Tokenizer._attach_tokens (spacy/tokenizer.cpp:6444)
  File "spacy/tokens/doc.pyx", line 282, in spacy.tokens.doc.Doc.push_back (spacy/tokens/doc.cpp:8356)
AssertionError
```

**Comment by yxtay** [comment] 2016-06-30 02:48
I am also facing this issue with spaCy 0.100.7. Similar text data on spaCy 0.100.6 works fine.

**Comment by gojomo** [comment] 2016-08-22 22:35
Getting same error here.

**Comment by rajpurkar** [comment] 2016-08-23 09:39
Update to the latest version of spacy (or 0.101.0, which is what i'm using)
This was definitely a problem in 0.100.7, but the update should solve the problem

**Comment by honnibal** [comment] 2016-08-23 17:06
Is it safe to close this?

Also, is there an issue holding people on 0.100.7 specifically?

**Comment by gojomo** [comment] 2016-08-23 19:28
I got 0.100.7 from the conda channel recommended in the Spacy docs a couple days ago, so expected that would be the latest/recommended version. Should whatever's at PyPI be generally preferred?

**Comment by honnibal** [comment] 2016-08-23 19:35
Ah, dammit. Yes conda is out of date, because the Macstadium servers that were part of our build/test service got wound up before 0.101.0 was released. The details are a little hazy to me --- I was never doing the conda builds. 

There's a bit of infrastructure that needs to be replaced. For now, yes --- install off PyPi.

**Comment by gojomo** [comment] 2016-08-23 22:16
No worries, thanks for the clarification! As the issue is fixed (and upgrade-guidance is clear), seems OK to close.

**Closed** 2016-08-23 22:17 UTC
